### ISSUE TITLE
wrong command in the content  in KMCLib 1.1 documentation - Make system

### ISSUE THREAD

**Issue by Abel-Ding** [leetmaa/KMCLib#15]
in the paragraph Make system:

> Make system
> The make system is based on CMake. Installing CMake can be done by typing on Ubuntu:
> 
> **sudo apt-get install swig**
> 
> and on Mac OSX using macports:
> 
> **sudo port install swig && sudo port install swig-python**

The command for installation of CMake is wrong,  it is the installation of swig which is the same with the next paragraph.

I am using ubuntu 14, is Cmake 3.5.1 proper for  kMClib?

**Comment by leetmaa** [comment]
Thank you for pointing this out. I'll fix this error for version 2.0.

As for your other question, try to use CMake 3.5.1. If all tests run properly you're fine, if they don't try to fix it and post the solution. Or open a new issue.

Cheers!
