### ISSUE TITLE
Abort Trap 6 mistake

### ISSUE THREAD

**Issue by hezhengda** [leetmaa/KMCLib#17]
Dear KMCLib developer,
Thank you for this amazing software. I've been searching for similar programs for a long time.
The installation is successful, but when I do "python utest.py", an error occured:

**Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6**

Could you help me fix this ?
Thanks,
Zhengda

**Comment by leetmaa** [comment]
This seems like an MPI error. Is the problem solved? What was the solution?

**Comment by leetmaa** [comment]
Please re-open the issue if this is still an issue. I'll close it for now.
