### ISSUE TITLE
KMCRateCalculatorPlugin question

### ISSUE THREAD

**Issue by alberthxf** [leetmaa/KMCLib#2]
Hi, Mikael, I find I can't input any parameters for my own rate calculator. In KMCInteractions, the rate_calculator under setRateCalculator should be a class, not object. I can't provide any specific parameters into my own rate calculator. For example, I want to make the rate to be temperature related. I can't input the temperature except use a global variable. Do I understand correct?

Best,
Albert

**Comment by alberthxf** [comment]
I think I know the answer. The rate_constant can be a potential parameter. But I think it may be better if extra parameters can be input into the own rate calculator.

**Comment by leetmaa** [comment]
I see the appeal of sending information to the constructor. However that would also require the user who wants to implement a custom rate calculator to call the backend C++ rate calculator constructor properly. I will think about this behaviour for the 2.0 release, where C++ custom rate calculators also will be supported, and I'll keep this question in mind. But until then you'll have to go for a global variable to get the temperature in there.
