### ISSUE TITLE
Typo in MSD output

### ISSUE THREAD

**Issue by aschankler** [leetmaa/KMCLib#23]
The header of the output produced by `printResults` has a key 'DSD_y' rather than 'MSD_y'.

https://github.com/leetmaa/KMCLib/blob/4513accea266c934dbdceab4fe9fad9ba58e9750/python/src/KMCLib/Analysis/OnTheFlyMSD.py#L289

**Comment by leetmaa** [comment]
Thanks for pointing this out. It should be fixed now.
