### ISSUE TITLE
linking libstdc++ statically

### ISSUE THREAD

**Issue by PytLab** [leetmaa/KMCLib#4]
Hi Leetmaa:
Is it better to link libstdc++ statically by adding `-static-libstdc++` compiler option for compatible working in different linux?

ShaoZhengjiang

**Comment by leetmaa** [comment]
There are a few options if you want to deploy the executable. The accepted answer and the following discussion on this question it a good guide: http://stackoverflow.com/questions/13636513/linking-libstdc-statically-any-gotchas
